### ISSUE TITLE
Library Refactoring

### ISSUE THREAD

**Issue by Taym95** [omdxp/leblad-rs#41]
Thank you for this library! Keep the good work!

I suggest utilizing Rust language features for improved readability. For instance:

https://github.com/omdxp/leblad-rs/blob/f527ab7115c5143d6ab68c7caed31dd0d0f56353/src/lib.rs#L254

can be simplified using Rust iterators and combinators like this:

```
pub fn get_first_phone_code_for_wilaya(wilaya_name: &str) -> Option<u16> {
    ALL_WILAYAS
        .iter()
        .find(|wilaya| wilaya.name == wilaya_name)
        .map(|wilaya| wilaya.phone_codes[0])
}
```

Also accessing the first element using indexing, like `wilaya.phone_codes[0]`, is usually considered a code smell. It's better to use .first() and handle the case when the vector is empty for some reason

same for all other functions

**Comment by omdxp** [comment]
Thanks @Taym95 for your suggestions! I'll apply them for the next patch
